name: Scrape DaddyLive

on:
  schedule:
    - cron: '0 4 * * *'  # ทุกวัน 04:00 น. (UTC)
  workflow_dispatch:     # สามารถรัน manual ได้

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install aiohttp beautifulsoup4 lxml

      - name: Run scraper
        run: |
          python scraper.py

      - name: Commit & Push results
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add daddytv.json daddytv.m3u
          git commit -m "Update DaddyLive {{ github.run_number }}" || echo "No changes"
          git push
